apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: default
spec:
  selector:
    app: apache
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: mysvc
    protocol: TCP
    port: 80
    targetPort: 80